export const skillsAndTechnologies: string[] = [
  'JavaScript', 'Python', 'Java', 'C++', 'C#', 'Ruby', 'Go', 'PHP', 'Swift', 'Kotlin',
  'HTML', 'CSS', 'TypeScript', 'SQL', 'NoSQL', 'MongoDB', 'MySQL', 'PostgreSQL', 'GraphQL',
  'REST API', 'Django', 'Flask', 'Spring Boot', 'ASP.NET', 'Node.js', 'Express.js',
  'React', 'Angular', 'Vue', 'Svelte', 'Next.js', 'Nuxt.js', 'Gatsby',
  'Docker', 'Kubernetes', 'CI/CD', 'Git', 'GitHub', 'GitLab', 'Jenkins',
  'AWS', 'Azure', 'Google Cloud Platform', 'Firebase', 'Heroku', 'Terraform', 'Ansible',
  'Linux', 'Unix', 'Windows', 'MacOS', 'Bash', 'PowerShell',
  'Machine Learning', 'Deep Learning', 'Artificial Intelligence', 'NLP',
  'Data Science', 'Data Analysis', 'Data Engineering', 'Big Data', 'Hadoop', 'Spark',
  'Tableau', 'Power BI', 'Excel', 'R', 'Matplotlib', 'Pandas',
  'Blockchain', 'Ethereum', 'Solidity', 'Smart Contracts',
  'Cybersecurity', 'Network Security', 'Penetration Testing', 'Cryptography',
  'UI/UX Design', 'Adobe Photoshop', 'Adobe Illustrator', 'Sketch', 'Figma', 'Adobe XD',
  'Agile Methodologies', 'Scrum', 'Kanban', 'Project Management', 'Jira', 'Trello',
  'Digital Marketing', 'SEO', 'Content Marketing', 'Social Media Marketing', 'Google Analytics',
  'A/B Testing', 'Conversion Rate Optimization', 'Email Marketing', 'Copywriting', 'Branding',
  'Visual Studio Code', 'IntelliJ IDEA', 'Eclipse', 'PyCharm', 'Xcode', 'Android Studio',
  'NetBeans', 'Vim', 'Atom', 'Sublime Text', 'WebStorm', 'Postman', 'Insomnia',
  'Webpack', 'Babel', 'Gulp', 'Grunt', 'Rollup', 'Parcel', 'NPM', 'Yarn',
  'Redis', 'Elasticsearch', 'Cassandra', 'Neo4j', 'Firebase Realtime Database',
  'Snowflake', 'BigQuery', 'Redshift', 'Apache Cassandra', 'CouchDB', 'Oracle DB',
  'Communication', 'Teamwork', 'Problem Solving', 'Critical Thinking', 'Time Management',
  'Adaptability', 'Creativity', 'Work Ethic', 'Interpersonal Skills', 'Leadership',
  'Emotional Intelligence', 'Conflict Resolution', 'Decision Making', 'Attention to Detail',
  'Active Listening', 'Empathy', 'Negotiation', 'Self-Motivation', 'Resilience',
  'Collaboration', 'Customer Orientation', 'Professionalism', 'Stress Management', 'Patience',
  'Financial Analysis', 'Accounting', 'Bookkeeping', 'Budgeting', 'Forecasting',
  'Strategic Planning', 'Business Development', 'Market Research', 'Customer Service',
  'Sales', 'CRM Management', 'Vendor Management', 'Supply Chain Management',
  'Human Resources', 'Recruitment', 'Onboarding', 'Training and Development',
  'Legal Compliance', 'Policy Implementation', 'Risk Management', 'Event Planning', 'Content Creation', 'Editing', 'Technical Writing', 'Public Speaking',
  'Brand Management', 'Customer Relationship Management', 'Procurement',
  'Business Analysis', 'Change Management', 'Competitive Analysis', 'Operations Management',
  'Animation', '3D Modeling', 'Video Editing', 'Film Production',
  'Audio Editing', 'Sound Design', 'Motion Graphics', 'Product Design',
  'Industrial Design', 'Fashion Design', 'Interior Design',
  'Creative Direction', 'Art Direction', 'Illustration', 'Storyboard Creation',
  'Mechanical Engineering', 'Electrical Engineering', 'Civil Engineering',
  'CAD (Computer-Aided Design)', 'SolidWorks', 'Fusion 360', 'Mathematica',
  'PLC Programming', 'Embedded Systems', 'Robotics', 'RF Engineering', 'PCB Design',
  'Finite Element Analysis (FEA)', 'Quality Control', 'Six Sigma', 'Lean Manufacturing',
  'Data Mining', 'Statistical Modeling', 'Predictive Modeling',
  'Cluster Analysis', 'Regression Analysis', 'Classification',
  'Natural Language Processing (NLP)', 'Neural Networks', 'TensorFlow', 'PyTorch',
  'Apache Kafka', 'Dask', 'Big Data Engineering', 'Data Visualization', 'Exploratory Data Analysis',
  'Inventory Management', 'Quality Assurance', 'Data Entry', 'Administrative Support',
  'Microsoft Office', 'MS Word', 'MS Excel', 'MS PowerPoint', 'Google Workspace',
  'Statistical Analysis', 'Supply Chain', 'Inventory Control', 'E-commerce', 'Salesforce',
  'Zendesk', 'Help Desk', 'SAP', 'Oracle ERP', 'QuickBooks',
  'Presentation Skills', 'Mentorship', 'Research', 'Public Relations', 'Advertising',
  'Client Relations', 'Product Management', 'Product Lifecycle Management',
  'Compliance', 'Environmental Sustainability', 'Risk Analysis', 'Customer Success',
  'Market Intelligence', 'Proposal Writing', 'Customer Feedback Management',
  'Behavioral Analysis', 'Conflict Management', 'Event Management', 'Cultural Awareness',
  'Ethical Hacking', 'IT Support', 'Network Troubleshooting', 'Web Development',
  'Mobile Development', 'Game Development', 'Software Development',
  'Cloud Computing', 'DevOps', 'Microservices Architecture', 'Server Management',
  'Data Governance', 'Data Warehousing', '3D Printing', 'Automated Testing', 'Selenium',
  'JUnit', 'Jasmine', 'Cypress', 'End-to-End Testing', 'Load Testing', 'Security Testing',
  'Threat Modeling', 'Vulnerability Assessment', 'Incident Response'
];


export const steps = [
  { label: 'Personal Details', icon: 'account_circle' },
  { label: 'Work Experience', icon: 'work' },
  { label: 'Projects', icon: 'terminal' },
  { label: 'Skills', icon: 'psychology' },
  { label: 'Social Links', icon: 'link' },
];

export const stepDescriptions = [
  'Provide your personal details like name, email, and bio.',
  'List your previous work experience including company name, position, and duration.',
  'Share the projects you have worked on, including technologies used and links to the projects.',
  'Detail your skills and expertise areas.',
  'Add your social media and professional links such as LinkedIn, GitHub, etc.',
];