export type KEYS = { p256dh: string; auth: string };

export type PUSHNOTIFICATION = {
  endpoint: string;
  expirationTime?: string | null;
  keys: KEYS;
};

export enum USERTYPE {
  MEMBER = 'MEMBER',
  CLIENT = 'CLIENT',
}

export enum USERSTATUS {
  ACTIVE = 'ACTIVE',
  INACTIVE = 'INACTIVE',
  BLOCKED = 'BLOCKED',
}

export enum USERROLE {
  CORETEAM = 'CORETEAM',
  ASSOCIATE = 'ASSOCIATE',
  FREELANCER = 'FREELANCER',
  INTERN = 'INTERN',
  TRIAL_CANDIDATE = 'TRIAL_CANDIDATE',
}

export enum USERVERTICAL {
  DEV = 'DEV',
  DESIGN = 'DESIGN',
  MARKETING = 'MARKETING',
  COMMUNITY = 'COMMUNITY',
  FINANCE = 'FINANCE',
  LEGAL = 'LEGAL',
  HR = 'HR',
  OPERATIONS = 'OPERATIONS',
}

export enum HOUSEID {
  MANAGEMENT = 'MANAGEMENT',
  GROWTH = 'GROWTH',
  PRODUCT_TECH = 'PRODUCT_TECH',
  EXECUTIVE = 'EXECUTIVE',
}

export enum USERINDUSTRY {
  CRYPTO = 'CRYPTO',
  FINANCE = 'FINANCE',
  HEALTHCARE = 'HEALTHCARE',
  EDUCATION = 'EDUCATION',
  RETAIL = 'RETAIL',
  REALSTATE = 'REALSTATE',
  GAMING = 'GAMING',
  SOCIAL = 'SOCIAL',
  OTHERS = 'OTHERS',
}

export enum NotificationType {
  ADMIN = 'ADMIN',
  SELF_GENERATED = 'SELF_GENERATED',
  USER_TO_USER = 'USER_TO_USER',
}

export enum BadgeType {
  CUSTOM = 'CUSTOM',
  STREAK = 'STREAK',
  TIME_BASED = 'TIME_BASED',
}

export enum StreakType {
  WORKLOG_BASED = 'WORKLOG_BASED',
  TASK_BASED = 'TASK_BASED',
  MISSION_BASED = 'MISSION_BASED',
  ARTICLE_BASED = 'ARTICLE_BASED',
}

export enum BadgeStatus {
  INACTIVE = 'INACTIVE',
  ACTIVATED = 'ACTIVATED',
  REWARDED = 'REWARDED',
  SUSPENDED = 'SUSPENDED',
}

export enum BUFF_LEVEL {
  TRUTH_SEEKER = 'TRUTH_SEEKER',
  BABY_GROOT = 'BABY_GROOT',
  WORK_HULK = 'WORK_HULK',
  VAMPIRE_LORD = 'VAMPIRE_LORD',
  ALIEN_PREDATOR = 'ALIEN_PREDATOR',
  DEVIL = 'DEVIL',
}
