name: Cleanup PR Preview Environments

on:
  pull_request:
    types: [closed]

permissions:
  contents: write
  pull-requests: write

concurrency:
  group: ${{ github.repository }}-pr-${{ github.event.pull_request.number }}
  cancel-in-progress: true

jobs:
  cleanup_on_pr_close:
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH (secured)
        uses: webfactory/ssh-agent@v0.9.0
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
          log-public-key: false

      - name: Cleanup Deployments
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} << 'EOF'
            # Ensure profile is loaded (fix for PM2 in non-interactive shells)
            source ~/.bashrc || true
            source ~/.profile || true

            # Stop and remove PM2 processes using jlist and jq for reliability
            pm2 jlist | jq -r --arg PR "portal-${{ github.event.pull_request.number }}" '.[] | select(.name | test($PR)) | .pm_id' | xargs -r pm2 delete
            pm2 jlist | jq -r --arg PR "payzone-${{ github.event.pull_request.number }}" '.[] | select(.name | test($PR)) | .pm_id' | xargs -r pm2 delete
            
            # Remove deployment directories

            cd /home/${{ secrets.DROPLET_USER }}/apps/builds/portal/preview/
            rm -rf ${{ github.event.pull_request.number }}/
            cd /home/${{ secrets.DROPLET_USER }}/apps/builds/payzone/preview/
            rm -rf ${{ github.event.pull_request.number }}/
            
            echo "Cleaned up PR #${{ github.event.pull_request.number }}"
          EOF
