name: Approve Preview Deployment

on:
  workflow_dispatch:
    inputs:
      project:
        description: "Project name (payzone, portal, home)"
        required: true
      pr_number:
        description: "Pull request number"
        required: true

jobs:
  approve:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Approve Preview Deployment
        run: |
          ssh -o StrictHostKeyChecking=no techteam@${{ secrets.DROPLET_IP }} <<EOF
            cd ${{ github.event.inputs.project }}
            git fetch origin pull/${{ github.event.inputs.pr_number }}/head:pr-${{ github.event.inputs.pr_number }}
            git checkout pr-${{ github.event.inputs.pr_number }}
            npm install
            npm run build
            PORT=$((8000 + ${{ github.event.inputs.pr_number }}))

            # Restart or start the PM2 process for the PR
            if pm2 list | grep -q "${{ github.event.inputs.project }}-pr-${{ github.event.inputs.pr_number }}"; then
              pm2 restart ${{ github.event.inputs.project }}-pr-${{ github.event.inputs.pr_number }};
            else
              pm2 start --name ${{ github.event.inputs.project }}-pr-${{ github.event.inputs.pr_number }} "npm run start";
            fi
          EOF
