name: Cleanup
on:
  workflow_dispatch:
    inputs:
      action:
        description: 'Action to perform (cleanup)'
        required: true

jobs:
  cleanup:
    if: github.event.inputs.action == 'cleanup'
    runs-on: ubuntu-latest
    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}
      - name: Remove Preview Deployment
        run: |
          ssh -o StrictHostKeyChecking=no techteam@${{ secrets.DROPLET_IP }} <<EOF
            pm2 delete payzone-pr-${{ github.event.number }} || true
            pm2 delete portal-pr-${{ github.event.number }} || true
          EOF
