name: Cleanup Preview Deployment

on:
  workflow_dispatch:
    inputs:
      project:
        description: 'Project name (payzone, portal, home)'
        required: true
      pr_number:
        description: 'Pull request number'
        required: true

jobs:
  cleanup:
    runs-on: ubuntu-latest
    permissions:
      contents: write

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Remove Preview Deployment
        run: |
          ssh -o StrictHostKeyChecking=no techteam@${{ secrets.DROPLET_IP }} <<EOF
            pm2 delete ${{ github.event.inputs.project }}-pr-${{ github.event.inputs.pr_number }} || true
          EOF
