name: Comment Actions

on:
  issue_comment:
    types:
      - created

permissions:
  contents: write
  pull-requests: write

jobs:
  handle-comment:
    runs-on: ubuntu-latest
    steps:
      - name: Extract PR Number and Action
        id: extract
        run: |
          PR_NUMBER=$(echo "${GITHUB_CONTEXT}" | jq -r '.issue.pull_request.url | sub(".*/"; "") | sub("/pull/[0-9]+"; "")')
          ACTION=$(echo "${{ github.event.comment.body }}" | awk '{for(i=1;i<=NF;i++) if ($i~/^@bot/) {print $i; exit}}' | cut -d''-f2)
          echo "PR_NUMBER=$PR_NUMBER" >> $GITHUB_ENV
          echo "ACTION=$ACTION" >> $GITHUB_ENV

      - name: Execute Action
        run: |
          if [ "${{ env.ACTION }}" = "cleanup" ]; then
            if [ -n "${{ env.PR_NUMBER }}" ]; then
              ssh -o StrictHostKeyChecking=no techteam@${{ secrets.DROPLET_IP }} <<EOF
                echo "Starting cleanup for PR #${{ env.PR_NUMBER }}..."
                pm2 delete payzone-pr-${{ env.PR_NUMBER }} || true
                pm2 delete portal-pr-${{ env.PR_NUMBER }} || true
                echo "Cleanup completed for PR #${{ env.PR_NUMBER }}."
              EOF
            else
              echo "Cannot perform cleanup without a PR number."
          elif [ "${{ env.ACTION }}" = "delete_lock" ]; then
            ssh -o StrictHostKeyChecking=no techteam@${{ secrets.DROPLET_IP }} <<EOF
              LOCK_FILE="/tmp/deploy/deploy-lock"
              if [ -f "$LOCK_FILE" ]; then
                rm -f "$LOCK_FILE"
                echo "Deploy lock file removed."
              else
                echo "No deploy lock file found."
              fi
            EOF
          else
            echo "Invalid action from comment. Please use '@bot cleanup' or '@bot delete_lock'."
          fi
        env:
          GITHUB_CONTEXT: ${{ github }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        if: contains(github.event.comment.body, '@bot') && (github.event.comment.body == '*@bot cleanup*' || github.event.comment.body == '*@bot delete_lock*')