name: Deploy and Update PM2 Cron

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy and Restart PM2 Cron Jobs
        run: |
          ssh -o StrictHostKeyChecking=no ${{ secrets.DROPLET_USER }}@${{ secrets.DROPLET_IP }} << "EOF"
            cd apps/moon-portal-app/portal
            # Stash any local changes before pulling the latest changes
            git stash || git reset --hard || true

            # Pull the latest changes
            git checkout main
            git pull origin main || { echo "ERROR: Failed to pull latest changes." >&2; git stash pop || true; rm -f "$LOCK_FILE"; exit 1; }

            # Start or restart the PM2 process using the ecosystem config
            pm2 startOrReload ecosystem.config.js || {
              echo "ERROR: Failed to start/reload PM2 process." >&2
              exit 1
            }

            # Apply stashed changes back
            git stash pop || echo "No stashed changes to pop."
            echo "CRON Deployment and PM2 restart successful."
          EOF
