name: Prettier Check
on:
  pull_request:
    branches:
      - "**"

jobs:
  prettier:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set up Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 18
          cache: 'npm'

      - name: Get changed files
        id: changed-files
        uses: tj-actions/changed-files@v41

      - name: Prettier Check - Payzone
        if: contains(steps.changed-files.outputs.all_changed_files, 'payzone/')
        run: |
          cd payzone
          npm ci
          npm run prettier:check

      - name: Prettier Check - Portal
        if: contains(steps.changed-files.outputs.all_changed_files, 'portal/')
        run: |
          cd portal
          npm ci
          npm run prettier:check

      - name: Prettier Check - Home
        if: contains(steps.changed-files.outputs.all_changed_files, 'home/')
        run: |
          cd home
          npm ci
          npm run prettier:check

      - name: Comment on PR if Prettier issues found
        if: failure()
        uses: actions/github-script@v6
        with:
          script: |
            github.rest.issues.createComment({
              issue_number: context.issue.number,
              owner: context.repo.owner,
              repo: context.repo.repo,
              body: '❌ Code formatting issues detected. Please run `npm run prettier:fix` in the relevant project directory and push the changes.'
            })