name: Production Deployment

on:
  push:
    branches:
      - main

permissions:
  contents: write

jobs:
  determine_project:
    runs-on: ubuntu-latest
    outputs:
      projects: ${{ steps.set-projects.outputs.projects }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Determine changed projects
        id: set-projects
        run: |
          git fetch --prune
          git fetch origin +refs/heads/*:refs/remotes/origin/*
          changed_files=$(git diff --name-only ${{ github.event.pull_request.base.sha }} ${{ github.event.pull_request.head.sha }})
          project_paths=("portal" "payzone" "home")
          projects=()
          home_changed=false
          if echo "$changed_files" | grep -q "^home/"; then
            home_changed=true
          fi
          if echo "$changed_files" | grep -q "^portal/"; then
            projects+=("portal")
          fi
          if echo "$changed_files" | grep -q "^payzone/"; then
            projects+=("payzone")
          fi
          if ! $home_changed && [ ${#projects[@]} -eq 0 ] && echo "$changed_files" | grep -vq "^portal/" && echo "$changed_files" | grep -vq "^payzone/" && echo "$changed_files" | grep -vq "^home/"; then
            projects=("portal" "payzone")
          fi
          echo "Changed projects: ${projects[@]}"
          echo "projects=$(jq -c -n --argjson projects "$(printf '%s\n' "${projects[@]}" | jq -R . | jq -s .)" '$projects')" >> $GITHUB_OUTPUT
      - name: Debug Changed Projects Output
        run: |
          echo "Projects output: ${{ steps.set-projects.outputs.projects }}"

  deploy:
    needs: determine_project
    if: needs.determine_project.outputs.projects != 'null' && needs.determine_project.outputs.projects != '[]'
    runs-on: ubuntu-latest
    timeout-minutes: 10
    strategy:
      matrix:
        project: ${{ fromJson(needs.determine_project.outputs.projects) }}
      max-parallel: 1 # Ensure deployments run sequentially
    concurrency:
      group: main-deployment # Queue all deployments into a single group
      cancel-in-progress: false

    steps:
      - name: Set up SSH
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Deploy Prod to DigitalOcean
        run: |
          ssh -o StrictHostKeyChecking=no techteam@${{ secrets.DROPLET_IP }} << "EOF"
            LOCK_FILE="/tmp/deploy/deploy-lock"  # Unified lock file for all projects
            echo "Checking for ongoing deployments..."

            # Wait if the lock file exists
            while [ -f "$LOCK_FILE" ]; do
              echo "Deployment lock exists. Waiting..."
              sleep 10
            done

            touch "$LOCK_FILE"
            echo "Starting production deployment for project: ${{ matrix.project }}"

            cp -r /home/techteam/apps/moon-portal-app/${{ matrix.project }}/build/main /home/techteam/apps/moon-portal-app/${{ matrix.project }}/build/main-backup

            # Change to the project directory
            export NEXT_PUBLIC_BUILD_PATH=main
            cd apps/moon-portal-app/${{ matrix.project }}/build

            # Stash any local changes before pulling the latest changes
            git stash || true

            # Pull the latest changes
            git checkout main
            git pull origin main || { echo "ERROR: Failed to pull latest changes." >&2; git stash pop || true; rm -f "$LOCK_FILE"; exit 1; }

            # Apply stashed changes back
            git stash pop || true

            # Install dependencies and build with error handling
            if ! npm install; then
              echo "ERROR: npm install failed. Cleaning up..." >&2
              git stash pop || echo "No stashed changes to pop."
              rm -f "$LOCK_FILE"
              exit 1
            fi
            
            if ! npm run build:prod; then
              echo "ERROR: Build failed. Cleaning up..." >&2
              git stash pop || echo "No stashed changes to pop."
              rm -f "$LOCK_FILE"
              exit 1
            fi

            # Restart the PM2 process for the project
            if pm2 list | grep -q "${{ matrix.project }}-main"; then
              pm2 restart ${{ matrix.project }}-main --update-env || {
                echo "ERROR: Failed to restart PM2 process. Cleaning up..." >&2
                git stash pop || echo "No stashed changes to pop."
                rm -f "$LOCK_FILE"
                exit 1
              }
            else
              pm2 start npm --name ${{ matrix.project }}-main -- run start || {
                echo "ERROR: Failed to start PM2 process. Cleaning up..." >&2
                git stash pop || echo "No stashed changes to pop."
                rm -f "$LOCK_FILE"
                exit 1
              }
            fi

            echo "Deployment completed for project: ${{ matrix.project }}"
          EOF

      - name: Cleanup Lock File
        if: failure() || cancelled() || always()
        run: |
          ssh -o StrictHostKeyChecking=no techteam@${{ secrets.DROPLET_IP }} << "EOF"
            LOCK_FILE="/tmp/deploy/deploy-lock"
            git stash pop || echo "No stashed changes to pop."
            rm -f "$LOCK_FILE"
          EOF
