export const teams = [
  {
    id: "9016017480",
    name: "TheMoonDevs",
    color: "#3e2724",
    avatar: null,
    members: [
      {
        user: {
          id: 88998245,
          username: "Mriganka Mousum Gogoi",
          email: "mrigankagogoiofficial@gmail.com",
          color: "#ee5e99",
          profilePicture: null,
          initials: "MG",
          role: 3,
          custom_role: null,
          last_active: "1723745593529",
          date_joined: "1722319150755",
          date_invited: "1722316964661",
        },
        invited_by: {
          id: 88845706,
          username: "Shivanshu Tripathi",
          color: "#afb42b",
          email: "tshivanshu29@gmail.com",
          initials: "ST",
          profilePicture: null,
          banned_date: null,
          status: "active",
        },
      },
      {
        user: {
          id: 88974130,
          username: "Karthik Ayangar",
          email: "karthik.ayangar7118@gmail.com",
          color: "#1b5e20",
          profilePicture:
            "https://attachments.clickup.com/profilePictures/88974130_xwb.jpg",
          initials: "KA",
          role: 3,
          custom_role: null,
          last_active: "1726395929254",
          date_joined: "1719904334367",
          date_invited: "1719902339073",
        },
        invited_by: {
          id: 88845706,
          username: "Shivanshu Tripathi",
          color: "#afb42b",
          email: "tshivanshu29@gmail.com",
          initials: "ST",
          profilePicture: null,
          banned_date: null,
          status: "active",
        },
      },
      {
        user: {
          id: 88946178,
          username: "Anmol Atrey",
          email: "anmol.atrey@gmail.com",
          color: "#02579b",
          profilePicture: null,
          initials: "AA",
          role: 3,
          custom_role: null,
          last_active: "1723532936836",
          date_joined: "1716793761138",
          date_invited: "1716793056603",
        },
        invited_by: {
          id: 88805908,
          username: "Pramod Geddam",
          color: "#02579b",
          email: "aicodebox@gmail.com",
          initials: "PG",
          profilePicture: null,
          banned_date: null,
          status: "active",
        },
      },
      {
        user: {
          id: 88902830,
          username: "Manish",
          email: "manishguhe301@gmail.com",
          color: "#1090e0",
          profilePicture: null,
          initials: "M",
          role: 3,
          custom_role: null,
          last_active: "1726393522566",
          date_joined: "1711952065450",
          date_invited: "1711949220790",
        },
        invited_by: {
          id: 61383243,
          username: "Subhakar Tikkireddy",
          color: "#827718",
          email: "subhakartikkireddy@gmail.com",
          initials: "ST",
          profilePicture: null,
          banned_date: null,
          status: "active",
        },
      },
      {
        user: {
          id: 88895727,
          username: "Aruwajoye Oluwaseun",
          email: "sketchnaija@gmail.com",
          color: "#e040fb",
          profilePicture: null,
          initials: "AO",
          role: 3,
          custom_role: null,
          last_active: "1720714377580",
          date_joined: "1711005879321",
          date_invited: "1711005177840",
        },
        invited_by: {
          id: 61383243,
          username: "Subhakar Tikkireddy",
          color: "#827718",
          email: "subhakartikkireddy@gmail.com",
          initials: "ST",
          profilePicture: null,
          banned_date: null,
          status: "active",
        },
      },
      {
        user: {
          id: 78808612,
          username: "vishwajeet",
          email: "vishwajeety14122@gmail.com",
          color: "",
          profilePicture: null,
          initials: "V",
          role: 3,
          custom_role: null,
          last_active: "1726350619251",
          date_joined: "1709552169082",
          date_invited: "1709550436718",
        },
        invited_by: {
          id: 88805908,
          username: "Pramod Geddam",
          color: "#02579b",
          email: "aicodebox@gmail.com",
          initials: "PG",
          profilePicture: null,
          banned_date: null,
          status: "active",
        },
      },
      {
        user: {
          id: 88856748,
          username: "Koral Sharma",
          email: "koral.sharma10@gmail.com",
          color: "#64c6a2",
          profilePicture: null,
          initials: "KS",
          role: 3,
          custom_role: null,
          last_active: "1723635394626",
          date_joined: "1706592967269",
          date_invited: "1706591971783",
        },
        invited_by: {
          id: 88805908,
          username: "Pramod Geddam",
          color: "#02579b",
          email: "aicodebox@gmail.com",
          initials: "PG",
          profilePicture: null,
          banned_date: null,
          status: "active",
        },
      },
      {
        user: {
          id: 88845706,
          username: "Shivanshu Tripathi",
          email: "tshivanshu29@gmail.com",
          color: "#afb42b",
          profilePicture: null,
          initials: "ST",
          role: 2,
          custom_role: null,
          last_active: "1725829093919",
          date_joined: "1705058129630",
          date_invited: "1705057801018",
        },
        invited_by: {
          id: 88805908,
          username: "Pramod Geddam",
          color: "#02579b",
          email: "aicodebox@gmail.com",
          initials: "PG",
          profilePicture: null,
          banned_date: null,
          status: "active",
        },
      },
      {
        user: {
          id: 88844740,
          username: "Kshitij Srivastava",
          email: "kshitij.suraj@gmail.com",
          color: "#536cfe",
          profilePicture: null,
          initials: "KS",
          role: 3,
          custom_role: null,
          last_active: "1726074884648",
          date_joined: "1704953917005",
          date_invited: "1704953673696",
        },
        invited_by: {
          id: 88805908,
          username: "Pramod Geddam",
          color: "#02579b",
          email: "aicodebox@gmail.com",
          initials: "PG",
          profilePicture: null,
          banned_date: null,
          status: "active",
        },
      },
      {
        user: {
          id: 88815772,
          username: "Tarkesh Chaturvedi",
          email: "tarkesh.chat@gmail.com",
          color: "#263238",
          profilePicture: null,
          initials: "TC",
          role: 3,
          custom_role: null,
          last_active: "1726304011227",
          date_joined: "1700127037821",
          date_invited: "1700061873986",
        },
        invited_by: {
          id: 61383243,
          username: "Subhakar Tikkireddy",
          color: "#827718",
          email: "subhakartikkireddy@gmail.com",
          initials: "ST",
          profilePicture: null,
          banned_date: null,
          status: "active",
        },
      },
      {
        user: {
          id: 88805908,
          username: "Pramod Geddam",
          email: "aicodebox@gmail.com",
          color: "#02579b",
          profilePicture: null,
          initials: "PG",
          role: 2,
          custom_role: null,
          last_active: "1723787893820",
          date_joined: "1698303980000",
          date_invited: "1698242139669",
        },
        invited_by: {
          id: 61383243,
          username: "Subhakar Tikkireddy",
          color: "#827718",
          email: "subhakartikkireddy@gmail.com",
          initials: "ST",
          profilePicture: null,
          banned_date: null,
          status: "active",
        },
      },
      {
        user: {
          id: 61383243,
          username: "Subhakar Tikkireddy",
          email: "subhakartikkireddy@gmail.com",
          color: "#827718",
          profilePicture: null,
          initials: "ST",
          role: 1,
          custom_role: null,
          last_active: "1726393258932",
          date_joined: "1698138603003",
          date_invited: "1698138603003",
        },
      },
    ],
  },
];
